let fatos = [
    {ano: '19', fato: 'As mulheres ganham o direito ao voto nos EUA'},
    {ano: '19', fato: 'O partido comunista chinês é fundado'},
    {ano: '19', fato: 'O império britânico diminui'},
    {ano: '19', fato: 'Ocorreu o grande terremoto na região de Kanto, no Japão'},
    {ano: '19', fato: 'Joseph Stalin assume o lugar de Vladmir Lenin'},
    {ano: '19', fato: 'O estado americano processa John Thomas Scopes por ensinar evolucionismo em uma escola do Tennessee.'},
    {ano: '19', fato: 'Os EUA iniciam o seu sistema de autoestradas numeradas'},
    {ano: '19', fato: 'Charles Lindbergh se torna a primeira pessoa a pilotar um avião sobre o oceano atlântico sem escalas.'},
    {ano: '19', fato: 'Amelia Earhart se torna a primeira mulher a cruzar o atlântico pilotando um avião.'},
    {ano: '19', fato: 'Ocorre a quebra da bolsa de valores de Nova York.'},
    {ano: '19', fato: 'Ho Chi Minh funda o partido comunista do Vietnã'},
    {ano: '19', fato: 'A construção do Empire State Building é concluída.'},
    {ano: '19', fato: 'Hitler renúcia a sua cidadania austríaca e se torna alemão'},
    {ano: '19', fato: 'Franklin  D. Roosvelt é eleito presidente dos Estados Unidos'},
    {ano: '19', fato: 'Hitler se consolida no poder.'},
    {ano: '19', fato: 'O presidente Franklin Roosvelt anuncia o New Deal, criando o primeiro sistema de seguro social para aposentados do país.'},
    {ano: '19', fato: 'O corredor Afro-Americano Jesse Owens ganha 4 medalhas de ouro nas olimpíadas de Berlim durante o nazismo de Hitler.'},
    {ano: '19', fato: 'Trabalhadores da General Motors protestam por 44 dias ocupando a fábrica da GM e conseguem uma aumento de 5% no pagamento.'},
    {ano: '19', fato: 'O movimento anti-semita se inicia na Alemanha durante o Nazismo de Hitler.'},
    {ano: '19', fato: 'Tem início a segunda guerra mundial'},
    {ano: '19', fato: 'O McDonalds é fundado.'},
    {ano: '19', fato: 'Tropas japonesas atacam a base de Pearl Harbor'},
    {ano: '19', fato: 'Tropas americanas chegam a Irlanda do Norte para lutar na guerra da Europa.'},
    {ano: '19', fato: 'O químico suíço Albert Hoffman descobre acidentalmente o LSD'},
    {ano: '19', fato: 'Ocorre a invasão da Normandia pelas forças aliadas para tirar as tropas nazistas da França'},
    {ano: '19', fato: 'A segunda guerra mundial termina com ataques atômicos a Hiroshima e Nagazaki, que causaram a rendição do Japão.'},
    {ano: '19', fato: 'Tem início a geração Baby Boom, só em 1946 foram mais de 3.4 milhões de crianças nascidas só nos EUA.'},
    {ano: '19', fato: 'A Índia consegue sua independência do império britânico, mas acaba divida e se torna duas nações, a Índia, para os Hindús e o Paquistão, para os muçulmanos.'},
    {ano: '19', fato: 'Acontece o nascimento do estado de Israel'},
    {ano: '19', fato: 'É fundada a Organização do Tratado do Atlântico Norte, a OTAN, para combater a ameaça Soviética.'},
    {ano: '19', fato: 'Tem início a Guerra das Coréias, quando a Coréia do Norte invade a Coréia do Sul, despertando a resposta imediata dos Estados Unidos. A guerra dura três anos.'},
    {ano: '19', fato: 'Julius e Ethel Rosenberg são condenados a morte nos EUA por espionagem, após terem vazado informações sobre bombas atômicas para a União Soviética.'},
    {ano: '19', fato: 'Os Estados Unidos detonam a primeira bomba de hidrogênio.'},
    {ano: '19', fato: 'Os cientistas James Watson e Francis Crick, da Universidade de Cambridge, são os primeiros a explicar o funcionamento do DNA na replicação dos genes e a sua transmissão para as futuras gerações.'},
    {ano: '19', fato: 'Linda Brown vence a disputa contra o conselho de educação e a suprema corte americana julga inconstitucional a segregação racial em escolas.'},
    {ano: '19', fato: 'Rosa Parks faz história ao se recursas a se levantar e dar lugar a um branco no ônibus. Sua prisão leva a um boicote a empresa e a ascenção do Pastor Martin Luther King Jr.'},
    {ano: '19', fato: 'Protestos na Hungria por democracia acaba na morte de milhares após invasão do Exercito Vermelho da Comunista União Soviética.'},
    {ano: '19', fato: 'O president Dwight Eisenhower ordena as tropas federais que proteja 9 alunos afro-americanos que começaram a estudar no colégio Little Rock para alunos brancos, essa foi a primeira ação do governo federal contra a segregação racial no país.'},
    {ano: '19', fato: 'Os Estados Unidos lançam seu primeiro satélite, o Explorer 1.'},
    {ano: '19', fato: 'Fidel Castro invade cuba e se consolida no poder, dando início a ditadura comunista.'},
    {ano: '19', fato: 'O restaurante Woolworth se recusa a atender 4 jovens afro-americanos, desencadeando uma enorme onda de protestos que durou 6 meses e resultou no fim da segregação nos restaurantes.'},
    {ano: '19', fato: 'Ocorre a construção do muro de Berlin'},
    {ano: '19', fato: 'A União Soviética testa misseis em Cuba, a 145km ao sul de Miami, dando início a resposta dos EUA sob o comando de John F Kennedy. A resposta de Kennedy faz a União Soviética remover os mísseis de Cuba.'},
    {ano: '19', fato: 'John F. Kennedy é assassinado.'},
    {ano: '19', fato: 'O presidente Lyndon Johnson dá inicio a sua "Guerra à Pobreza", destacando a necessidade de reduzir a probreza, acabar acabar com a segregação racial e cuidar da saúde dos idosos do país. Lyndon Johnson criou ainda o ato dos direitos civis no mesmo ano.'},
    {ano: '19', fato: 'O assassinato de Jimmy Lee Jackson pelas tropas do Alabama desencadeia uma passeata em protesto. O evento ficou conhecido como Domingo Sangrento.'},
    {ano: '19', fato: 'Mao Zedong inicia o extermínio de seus rivais políticos. O líder comunista enviou diversos opositores para campos de reeducação e trabalho forçado, e assassinou diversos outros que se opuseram ao seu governo.'},
    {ano: '19', fato: 'Acontece a guerra dos seis dias. Síria, Jordânia, Iraque e Egito atacam Israel, a guerra termina em 6 dias, com um cessar fogo após Israel ocupar areas importantes dos 4 países.'},
    {ano: '19', fato: 'Martin Luther King é assassinado.'},
    {ano: '19', fato: 'Neil Armstrong, Buzz Aldrin e Michael Collins são as primeiras pessoas a pisarem na lua'},
    {ano: '19', fato: 'A guerra na ásia aumenta e desperta protestos anti-guerra nos Estados Unidos dado o involvimento do país no continente.'},
    {ano: '19', fato: 'New York Times publica documentos sobre o envolvimento do governo amerino na guerra do Vietnã'},
    {ano: '19', fato: 'O Presidente Anti-Comunista Richard Nixon faz sua primeira viagem oficial a China, com o objetivo de melhorar a relação entre os dois países.'},
    {ano: '19', fato: 'A suprema corte define que os estados podem impedir o aborto a partir do terceiro trimestre de gestação, exceto quando a gestação oferece risco a vida da mulher.'},
    {ano: '19', fato: 'O presidente Richard Nixon Renuncia durante o processo de impeachment causado pelo escandalo de Watergate.'},
    {ano: '19', fato: 'Dois anos depois as últimas tropas americanas deixarem o Vietnã, as tropas comunistas capturam Saigon.'},
    {ano: '19', fato: 'Dois jatos super-sônicos Concorde levatam voo simultâneamente. Um partindo de Londres para o Barein, e outro de Paris, para o Rio de Janeiro.'},
    {ano: '19', fato: 'Os primeiros computadores pessoais modernos começam a surgir'},
    {ano: '19', fato: 'Mais de 900 pessoas morrem em um suícidio em massa promovido por um culto em Jonestown, promovido por Jim Jones.'},
    {ano: '19', fato: 'O Irã se torna uma república islâmica'},
    {ano: '19', fato: 'Ronald Reagan é eleito presidente dos Estados Unidos.'},
    {ano: '19', fato: 'Surge a AIDS nos Estados Unidos'},
    {ano: '19', fato: 'Governo Mexicano diz a reserva federal dos Estados Unidos que o país não consegue pagar o empréstimo de 80 bilhões de dólares.'},
    {ano: '19', fato: 'Acontece o nascimento da Internet'},
    {ano: '19', fato: 'Desastre químico em Bophal, India, afeta mais de 600 mil pessoas, matando mais de 15 mil dessas. '},
    {ano: '19', fato: 'Ronald Reagan se encontra com o Secretário Geral da União Soviética, Mikhail Gorbachev'},
    {ano: '19', fato: 'A nave Challenger exploduiu 73 segundos após decolar do Cabo Canaveral, causando a morte de 7 astronautas.'},
    {ano: '19', fato: 'A bolsa Dow Jones tem uma queda de 508 pontos, uma situação pior que a da quebra de 1929.'},
    {ano: '19', fato: 'O Tenente Coronel Oliver North e o Vice Almirante John Pointdexter são indiciados por conspiração após venderem armas para o Irã a fim de facilitar a soltura de reféns americanos.'},
    {ano: '19', fato: 'Acontece a queda do muro de Berlin.'},
    {ano: '19', fato: 'Com o enfraquecimento da União Soviética e do comunismo, a Polônia dissolve o partido comunista e elege seu primeiro presidente, Lech Walesa.'},
    {ano: '19', fato: 'Os Estados Unidos vão para a guerra do oriente médio após Sadam Hussain invadir o Kuait.'},
    {ano: '19', fato: 'A guerra fria entre Rússia e os EUA termina semanas após o fim da União Soviética.'},
    {ano: '19', fato: 'É criada a União Européia.'},
    {ano: '19', fato: 'O site Amazon.com é lançado'},
    {ano: '19', fato: 'Ataque terrorista acontece em Olklahoma com a explosão de um caminhão-bomba.'},
    {ano: '19', fato: 'A ovelha Dolly é Clonada com sucesso'},
    {ano: '19', fato: 'A IBM Deep Blue se tornou a primeira máquina a derrotar um campeão do Xadrez, derrotando Garry Kasparov duas vezes e empatando com ele três vezes em 6 partidas.'},
    {ano: '19', fato: 'É lançado o buscador Google'},
    {ano: '19', fato: 'A OTAN inicia sua primeira campanha militar'},
    {ano: '19', fato: 'A estação espacial internacional é inaugurada.'},
    {ano: '19', fato: 'As torres gêmeas do World Trade Center são derrubadas em um ataque terrorista'},
    {ano: '19', fato: 'George W. Bush cria o departamento de segurança nacional.'},
    {ano: '19', fato: 'Os Estados Unidos inciam os ataques ao Iraque'},
    {ano: '19', fato: 'O Facebook é fundado'},
    {ano: '19', fato: 'o Furacão Katrina destrói New Orleans.'},
    {ano: '19', fato: 'Saddam Hussein é executado'},
    {ano: '19', fato: 'Apple anuncia seu primeiro smartphone, o iPhone'},
    {ano: '19', fato: 'O indicador Dow Jones despenca outra vez, dessa vez caindo 777 pontos.'},
    {ano: '19', fato: 'Barack Obama é eleito presidente dos Estados Unidos e se torna o primeiro presidente afro-americano do país.'},
    {ano: '19', fato: '11 trabalhadores morrem e 17 ficam feridos em uma explosão na costa da Lousiana em uma exploração de óleo.'},
    {ano: '19', fato: 'Bin Laden é assassinado.'},
    {ano: '19', fato: 'Cientistas do CERN descobrem uma nova partícula através do colisor de hadrons que eles acreditam ser o Bóson de Higgs, a chamada "Partícula de Deus".'},
    {ano: '19', fato: 'Edward Snowden expões segredos de estado dos Estados Unidos e de governos europeus sobre espionagem de outros países.'},
    {ano: '19', fato: 'O Presidente Russo Vladmir Putin orquestra anexar a Crimeia à Rússia, causando sanções dos líderes mundiais ao país.'},
    {ano: '19', fato: 'A nave New Horizon se torna o primeiro objeto criado pela humanidade a passar por Plutão e observar o planeta de perto.'},
    {ano: '19', fato: 'Donald Trump é eleito presidente dos Estados Unidos'},
    {ano: '19', fato: 'Em um espaço de 4 semanas, 3 furações atingem os Estados Unidos, Harvey, Irma e Maria atingiram o Texas, Florida e  o Caribe'},
    {ano: '19', fato: 'Queimadas destroem a Carolina do Norte'},
    {ano: '19', fato: 'Protestos ocorrem em Hong Kong contra tentativa da China de tirar a autonomia do país.'},
    {ano: '19', fato: 'Tem início a pandemia de COVID-19'}
];

export default livros;